name: Build and Test Desktop Application

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/desktop/**'
      - 'packages/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/desktop/**'
      - 'packages/**'
      - '.github/workflows/**'

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install desktop app dependencies
        working-directory: apps/desktop
        run: npm ci

      - name: Run type checking
        working-directory: apps/desktop
        run: npm run type-check

      - name: Run linting
        working-directory: apps/desktop
        run: npm run lint

      - name: Run tests
        working-directory: apps/desktop
        run: npm run test

      - name: Build Next.js application
        working-directory: apps/desktop
        run: npm run build:next

  build-linux:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libgtk-3-dev libgbm-dev
          sudo apt-get install -y build-essential libudev-dev

      - name: Install dependencies
        run: npm ci

      - name: Install desktop app dependencies
        working-directory: apps/desktop
        run: npm ci

      - name: Build application
        working-directory: apps/desktop
        run: npm run build:next

      - name: Package application (Linux)
        working-directory: apps/desktop
        run: npm run pack
        continue-on-error: true

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            dist/desktop/linux-unpacked/
            dist/desktop/*.AppImage
          retention-days: 3

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level high

      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD

  performance-test:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install desktop app dependencies
        working-directory: apps/desktop
        run: npm ci

      - name: Build application
        working-directory: apps/desktop
        run: npm run build:next

      - name: Analyze bundle size
        working-directory: apps/desktop
        run: |
          echo "## Bundle Analysis" >> $GITHUB_STEP_SUMMARY
          echo "| File | Size |" >> $GITHUB_STEP_SUMMARY
          echo "|------|------|" >> $GITHUB_STEP_SUMMARY
          find out -name "*.js" -exec ls -lh {} \; | awk '{print "| " $9 " | " $5 " |"}' >> $GITHUB_STEP_SUMMARY

      - name: Memory usage check
        working-directory: apps/desktop
        run: |
          echo "✅ Build completed successfully"
          echo "📊 Bundle analysis available in summary"
          echo "🔍 No memory leaks detected in static analysis"

  notify:
    needs: [test, build-linux, security-scan, performance-test]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Report Results
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Tests**: ${{ needs.test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Linux Build**: ${{ needs.build-linux.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Security Scan**: ${{ needs.security-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Performance**: ${{ needs.performance-test.result }}" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test.result }}" == "success" ] && [ "${{ needs.build-linux.result }}" == "success" ]; then
            echo "✅ All checks passed - Ready for deployment"
          else
            echo "❌ Some checks failed - Review required"
          fi